WIP: Turn off styler
cynkra/constructive pull request #199
Opened 2023-06-16 04:44 UTC by krlmlr

With only a few tweaks I get down to 9 test failures, pushed to this PR. Some of them look interesting.

To finish this:

- Revert the last commit
- Fix remaining tests (lazytest can help)
- Remove styler entirely

For #49.

2023-07-07 13:24 UTC, krlmlr commented
@moodymudskipper: I get inconsistent results between my local install and CI/CD. I'm running R 4.2, could this be a reason?

Would you like to finish this off?

2023-07-07 13:53 UTC, moodymudskipper commented
package versions can also be the problem since I have tests that construct gepolt objects for instance, they should be run conditionally if given package version is installed.

Re indention I see in my snapshot test failures : 

* wrong indention after function call `fun(` going to the line
* When a string goes to the next line it should not be indented (e.g. read.table constructor, and function defs we get from secrets), technically should also be the case for names between backquotes or infix ops that go to the line but unlikely to happen. Even if we ignore the issues of nested quotes in backquotes `%` we still have to deal with `'`, `"` and their escaped counterparts so we basically need to build a poor man's parser I think, go character by character, flag when we open a string, and find where we close it. this needs to be reapplied at every step, i.e. we can't just have indent = paste. Or maybe we can repair at last step only, by subtracting the amount of incorrect indents once.
* current implementation has inconsistent space before native pipe
* indention not always applied
 
I can take it, but not in the short term

2023-07-07 14:16 UTC, krlmlr commented
The weird formatting issues are a styler problem:

``` r
requireNamespace("styler")
structure(
  c("(function(x) {\n  x\n}) |>", "  (`environment<-`)(.GlobalEnv)"),
  class = "vertical"
)
#> (function(x) {
#>   x
#> }) |>
#>   x`environment<-`)(.GlobalEnv)
```

<sup>Created on 2023-07-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2023-07-07 18:43 UTC, krlmlr commented
This is now looking much better, only indentation issues left. I can start using this for my purposes, we want to fix these issues at some point.

2023-07-08 15:55 UTC, krlmlr commented
This builds on top of #204 and is now good enough for me. We need to think what to do about the final remaining indentation errors.

2023-07-08 15:57 UTC, krlmlr commented
The first two commits now *should* be applicable on top of the main branch.

2023-11-07 15:15 UTC, moodymudskipper requested changes
I identified the issues and will fix, will undo the ordered modification since it seems to me to be out of scope

2023-11-07 15:15 UTC, moodymudskipper commented on tests/testthat/_snaps/s3-ggplot2-ggplot.md
> +      }) |>
same as above

2023-11-07 15:15 UTC, moodymudskipper commented on tests/testthat/_snaps/s3-ggplot2-ggplot.md
> +          ggplot2::ylim(10, 45)
can be solved in .cstr_construct.ScalesList

2023-11-07 16:53 UTC, moodymudskipper commented
snapshots should be ok now. now phasing out styler

2023-11-07 17:42 UTC, moodymudskipper commented
@krlmlr This is is ready to merge as far as I'm concerned, do you want to review ?
* deparse_call gets a new collapse arg
* we add the class "constructive_code" which is basically "vertical" without styler
* styler and "vertical" are not used anymore
* a couple tweaks
* prettycode is moved to imports since it's not implied by styler anymore 

After this I propose a `maybe_highlight()` function to highlight only if prettycode is installed, an we can move it back to Suggests

2023-11-07 17:46 UTC, moodymudskipper approved these changes

2023-11-07 18:46 UTC, moodymudskipper commented
one snapshot works differently for ubuntu-22.04 because of an indention issue, not sure what the root issue is

2023-11-12 18:26 UTC, krlmlr commented
Thanks. How is the `"constructive_code"` class different from the `"glue"` class offered by {glue}? Seems good otherwise.

2023-11-13 11:55 UTC, moodymudskipper approved these changes
This should work with the fix I just pushed, we didn't spot the actual ident issue though so we might see some issues arise with the next R version. These will be easier to investigate in time.

2023-11-13 11:55 UTC, moodymudskipper commented on R/s3-ggplot2-Scale.R
> +      args$palette <- "scales::rescale_pal(range)"
range is undefined so that won't work, I pushed a fix

2023-11-13 12:00 UTC, moodymudskipper commented
The glue class doesn't highlight code, "constructive_code" uses {prettycode} and is really just the "vertical" class, except no need for styler.

2023-11-13 12:31 UTC, merged

2023-11-13 12:32 UTC, krlmlr commented
Thanks! Would you like to push to CRAN?